#!/bin/bash

# cd to project root
cd `dirname $0`

# Copy hooks
cp hooks/* .git/hooks

# Install spotify-app-remote library if it does not exist
spotify_app_remote_libary_location=https://github.com/spotify/android-sdk/releases/download/v7.0.0-appremote_v1.2.3-auth/spotify-app-remote-release-0.7.0.aar
spotify_app_remote_release_dir=dependencies/spotify-app-remote
spotify_app_remote_release_file=spotify-app-remote-release-0.7.0.aar

if [ ! -f "$spotify_app_remote_release_dir/$spotify_app_remote_release_file" ]; then
  echo "Downloading Spotify app remote library from GitHub"
  mkdir -p $spotify_app_remote_release_dir
  curl -sL "$spotify_app_remote_libary_location" --output "$spotify_app_remote_release_dir/$spotify_app_remote_release_file"
fi

# Install spotify-auth library if it does not exist
spotify_auth_library_location=https://github.com/spotify/android-sdk/releases/download/v7.0.0-appremote_v1.2.3-auth/spotify-auth-release-1.2.3.aar
spotify_auth_release_dir=dependencies/spotify-auth
spotify_auth_release_file=spotify-auth-release-1.2.3.aar

if [ ! -f "$spotify_auth_release_dir/$spotify_auth_release_file" ]; then
  echo "Downloading Spotify auth library from GitHub"
  mkdir -p $spotify_auth_release_dir
  curl -sL "$spotify_auth_library_location" --output "$spotify_auth_release_dir/$spotify_auth_release_file"
fi
