-keep class androidx.navigation.fragment.NavHostFragment
-keep class com.bruno.android.ui.shared.AvatarFragment
-keep class com.bruno.android.ui.shared.FallbackPlaylistFragment
-keep class com.google.android.gms.maps.SupportMapFragment
